# Generated by Django 3.1.1 on 2020-10-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbital', '0002_comment_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
