# Generated by Django 3.1.1 on 2020-10-10 21:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbital', '0003_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
