# Generated by Django 3.1.1 on 2021-01-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbital', '0004_auto_20201010_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to='orbital.new'),
        ),
    ]
